const router = require('express').Router();
const bodyPar = require('body-parser');
router.use(bodyPar.json());
const branchController = require('../controllers/branchController');
const positionController = require('../controllers/positionController');
//const empController = require('../controllers/empController');
const fixcostController = require('../controllers/fixcostController');
const benefitController = require('../controllers/benefitController');
const costDataController = require('../controllers/costDataController');
const vacationController = require('../controllers/vacationController');
const positionEmpController = require('../controllers/positionEmpController');
const branchAdditController = require('../controllers/branchAdditController');
const projectController = require('../controllers/projectController');
const teamController = require('../controllers/teamController');
const projectAdditController = require('../controllers/projectAdditController');

router.get('/branch', branchController.list);
router.get('/branch/:id', branchController.listById);
router.post('/branch', branchController.save);
router.put('/branch/:id', branchController.update);
router.delete('/branch/:id', branchController.delete);
router.get('/position', positionController.list);
router.get('/position/:id', positionController.listById);
router.post('/position', positionController.save);
router.put('/position/:id', positionController.update);
router.delete('/position/:id', positionController.delete);
//router.get('/emp', empController.list);
//router.get('/emp/:id', empController.listById);
//router.post('/emp', empController.save);
//router.put('/emp/:id', empController.update);
//router.delete('/emp/:id', empController.delete);
router.get('/fixcost', fixcostController.list);
router.get('/fixcost/:id', fixcostController.listById);
router.post('/fixcost', fixcostController.save);
router.put('/fixcost/:id', fixcostController.update);
router.delete('/fixcost/:id', fixcostController.delete);
router.get('/benefit', benefitController.list);
router.get('/benefit/:id', benefitController.listById);
router.post('/benefit', benefitController.save);
router.put('/benefit/:id', benefitController.update);
router.delete('/benefit/:id', benefitController.delete);
router.get('/costData', costDataController.list);
router.get('/costData/:id', costDataController.listById);
router.post('/costData', costDataController.save);
router.put('/costData/:id', costDataController.update);
router.delete('/costData/:id', costDataController.delete);
router.get('/vacation', vacationController.list);
router.get('/vacation/:id', vacationController.listById);
router.post('/vacation', vacationController.save);
router.put('/vacation/:id', vacationController.update);
router.delete('/vacation/:id', vacationController.delete);
router.get('/positionEmp', positionEmpController.list);
router.get('/positionEmp/:id', positionEmpController.listById);
router.post('/positionEmp', positionEmpController.save);
router.put('/positionEmp/:id', positionEmpController.update);
router.delete('/positionEmp/:id', positionEmpController.delete);
router.get('/branchAddit', branchAdditController.list);
router.get('/branchAddit/:id', branchAdditController.listById);
router.post('/branchAddit', branchAdditController.save);
router.put('/branchAddit/:id', branchAdditController.update);
router.delete('/branchAddit/:id', branchAdditController.delete);
router.get('/project', projectController.list);
router.get('/project/:id', projectController.listById);
router.post('/project', projectController.save);
router.put('/project/:id', projectController.update);
router.delete('/project/:id', projectController.delete);
router.get('/team', teamController.list);
router.get('/team/:id', teamController.listById);
router.post('/team', teamController.save);
router.put('/team/:id', teamController.update);
router.delete('/team/:id', teamController.delete);
router.get('/projectAddit', projectAdditController.list);
router.get('/projectAddit/:id', projectAdditController.listById);
router.post('/projectAddit', projectAdditController.save);
router.put('/projectAddit/:id', projectAdditController.update);
router.delete('/projectAddit/:id', projectAdditController.delete);



module.exports = router;
